"""Initial schema with all indexes

Revision ID: 297121c33488
Revises: 
Create Date: 2026-06-23 11:57:11.805854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297121c33488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.alter_column('color_hex',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_categories_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_share_links_active', ['is_active'], unique=False)
        batch_op.create_index('idx_share_links_token', ['access_token'], unique=False)
        batch_op.create_index('idx_share_links_writing', ['writing_id'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_tags_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('token_block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_type', sa.String(length=10), nullable=False, server_default='access'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index('ix_token_block_jti')
        batch_op.create_index('idx_token_block_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_token_block_jti', ['jti'], unique=False)
        batch_op.create_unique_constraint('uq_token_block_jti', ['jti'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index('ix_users_email')
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    with op.batch_alter_table('writing_tags', schema=None) as batch_op:
        batch_op.create_index('idx_writing_tags_tag_id', ['tag_id'], unique=False)

    with op.batch_alter_table('writings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_writings_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_writings_updated', ['user_id', 'updated_at'], unique=False)
        batch_op.create_index('idx_writings_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_writings_user_status', ['user_id', 'is_archived', 'is_favorite'], unique=False)
        batch_op.create_index('idx_writings_user_type', ['user_id', 'content_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writings', schema=None) as batch_op:
        batch_op.drop_index('idx_writings_user_type')
        batch_op.drop_index('idx_writings_user_status')
        batch_op.drop_index('idx_writings_user_created')
        batch_op.drop_index('idx_writings_updated')
        batch_op.drop_index('idx_writings_category_id')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('word_count')

    with op.batch_alter_table('writing_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_writing_tags_tag_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_index('idx_users_email')
        batch_op.create_index('ix_users_email', ['email'], unique=1)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('display_name')

    with op.batch_alter_table('token_block', schema=None) as batch_op:
        batch_op.drop_constraint('uq_token_block_jti', type_='unique')
        batch_op.drop_index('idx_token_block_jti')
        batch_op.drop_index('idx_token_block_created_at')
        batch_op.create_index('ix_token_block_jti', ['jti'], unique=1)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('token_type')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('idx_tags_user_id')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index('idx_share_links_writing')
        batch_op.drop_index('idx_share_links_token')
        batch_op.drop_index('idx_share_links_active')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('idx_categories_user_id')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('color_hex',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
