"""add sharing fields to share_links

Revision ID: 2c67ade19d6a
Revises: 297121c33488
Create Date: 2026-06-23 12:45:15.098504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c67ade19d6a'
down_revision = '297121c33488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_mode', sa.String(length=20), nullable=False, server_default='public'))
        batch_op.add_column(sa.Column('max_views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_viewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_share_links_mode', ['share_mode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index('idx_share_links_mode')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_attempts')
        batch_op.drop_column('last_viewed_at')
        batch_op.drop_column('max_views')
        batch_op.drop_column('share_mode')

    # ### end Alembic commands ###
